INFO:root:Received request with params: ImmutableMultiDict([('name', 'bleecker street'), ('location', 'new york'), ('limit', '10')])
ERROR:app.app:Exception on /restaurant/reviews [POST]
Traceback (most recent call last):
  File "/Users/lorenamesa/.pyenv/versions/3.6.2/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lorenamesa/.pyenv/versions/3.6.2/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lorenamesa/.pyenv/versions/3.6.2/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lorenamesa/.pyenv/versions/3.6.2/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/lorenamesa/.pyenv/versions/3.6.2/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lorenamesa/.pyenv/versions/3.6.2/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lorenamesa/Desktop/pizza_review/app/app.py", line 88, in get_restaurant_reviews
    restaurant_categories = list(map(lambda r: r.get('alias'), restaurant['categories']))
KeyError: 'categories'
